In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('Data.csv')

In [6]:
df.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code number           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Uniformity of Cell Size      683 non-null    int64
 3   Uniformity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    int64
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [8]:
X = df.iloc[:, 1:-1].values
y= df.iloc[:, -1].values

In [9]:
from sklearn.model_selection import train_test_split
X_test, X_train, y_test, y_train = train_test_split(X, y, test_size=0.2, random_state=0)

## **Logistic regression classifier**


In [10]:
## standardizing the x_test and x_train just for the logistic regression
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_trainL = sc.fit_transform(X_train)

X_testL = sc.fit_transform(X_test)

In [11]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_trainL, y_train)

LogisticRegression(random_state=0)

In [12]:
y_test_predictL = classifier.predict(X_testL)

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
confuse = confusion_matrix(y_test, y_test_predictL)
print(f"consusion matrix is: \n {confuse}")

accurate = accuracy_score(y_test, y_test_predictL)
print(f"accuracy score is: {accurate}")

consusion matrix is: 
 [[348   9]
 [  9 180]]
accuracy score is: 0.967032967032967


## **K neerest neighbors**

In [14]:
sc1 = StandardScaler()
X_trainKNN = sc1.fit_transform(X_train)
X_testKNN = sc1.fit_transform(X_test)

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifierKNN = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski', n_jobs=None)
classifierKNN.fit(X_trainKNN, y_train)

KNeighborsClassifier()

In [16]:
y_predict_KNN = classifierKNN.predict(X_testKNN)

In [17]:
from sklearn.metrics import accuracy_score, pair_confusion_matrix
accuracyKNN = accuracy_score(y_test, y_predict_KNN)
confusionKNN = confusion_matrix(y_test, y_predict_KNN)
print(accuracyKNN)
print(confusionKNN)

0.9688644688644689
[[350   7]
 [ 10 179]]


### **naive bayes**


In [18]:
scNB = StandardScaler()
X_trainNB = sc.fit_transform(X_train)
X_testNB = sc.fit_transform(X_test)

In [19]:
from sklearn.naive_bayes import GaussianNB
classifierNB = GaussianNB()
classifierNB.fit(X_trainNB, y_train)

GaussianNB()

In [20]:
y_predict_NB = classifierNB.predict(X_testNB)

In [21]:
confuseNB = confusion_matrix(y_test, y_predict_NB)
print(f"consusion matrix is: \n {confuseNB}")

accurateNB = accuracy_score(y_test, y_predict_NB)
print(f"accuracy score is: {accurateNB}")

consusion matrix is: 
 [[342  15]
 [  4 185]]
accuracy score is: 0.9652014652014652


###**dicision trees**

In [22]:
scDT = StandardScaler()
X_trainDT = sc.fit_transform(X_train)
X_testDT = sc.fit_transform(X_test)

In [23]:
from sklearn.tree import DecisionTreeClassifier
classifierDT = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifierDT.fit(X_trainDT, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [24]:
y_predict_DT = classifierDT.predict(X_testDT)

In [25]:
confuseDT = confusion_matrix(y_test, y_predict_DT)
print(f"consusion matrix is: \n {confuseDT}")

accurateDT = accuracy_score(y_test, y_predict_DT)
print(f"accuracy score is: {accurateDT}")

consusion matrix is: 
 [[341  16]
 [ 12 177]]
accuracy score is: 0.9487179487179487


###**random forest**

In [26]:
scRF = StandardScaler()
X_trainRF = sc.fit_transform(X_train)
X_testRF = sc.fit_transform(X_test)

In [27]:
from sklearn.ensemble import RandomForestClassifier
classifierRF = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifierRF.fit(X_trainDT, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [28]:
y_predict_RF = classifierRF.predict(X_testDT)

In [29]:
accurateRF = accuracy_score(y_test, y_predict_RF)
print(f"accuracy score is: {accurateRF}")

confuseRF = confusion_matrix(y_test, y_predict_RF)
print(f"consusion matrix is: \n {confuseRF}")

accuracy score is: 0.9615384615384616
consusion matrix is: 
 [[349   8]
 [ 13 176]]


###**svm**

In [30]:
scSVM = StandardScaler()
X_trainSVM = sc.fit_transform(X_train)
X_testSVM = sc.fit_transform(X_test)

In [31]:
from  sklearn.svm import SVC
classifierSVM = SVC(kernel = 'linear', random_state = 0).fit(X_trainSVM, y_train)

In [32]:
y_predict_SVM = classifierSVM.predict(X_testSVM)

In [33]:
accurateSVM = accuracy_score(y_test, y_predict_SVM)
print(f"accuracy score is: {accurateSVM}")

confuseSVM = confusion_matrix(y_test, y_predict_SVM)
print(f"consusion matrix is: \n {confuseSVM}")

accuracy score is: 0.9560439560439561
consusion matrix is: 
 [[345  12]
 [ 12 177]]


###**kernel svm**

In [38]:
classifierKSVM = SVC(kernel='rbf', random_state=0).fit(X_trainSVM, y_train)

In [39]:
y_predict_KSVM = classifierKSVM.predict(X_testSVM)

In [41]:
accurateKSVM = accuracy_score(y_test, y_predict_KSVM)
print(f"accuracy score is: {accurateKSVM}")

confuseKSVM = confusion_matrix(y_test, y_predict_KSVM)
print(f"consusion matrix is: \n {confuseKSVM}")

accuracy score is: 0.9706959706959707
consusion matrix is: 
 [[349   8]
 [  8 181]]
